batch_size: 1

data:
  data_path: ./datasets/

model:
  
  use_image: true
  img_net: resnet18


  ev_graph:
    radius: 0.01
    max_neighbors: 16
    max_queue_size: 128

  base_width: 0.5
  after_pool_width: 1.0
  net_stem_width: 1.0
  num_scales: 2
  pooling_dim_at_output: 5x7
  keep_temporal_ordering: true

  activation: relu
  edge_attr_dim: 2
  aggr: sum
  kernel_size: 5
  pooling_aggr: max

  batch_size: ${batch_size}

  